apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cacetetinho
    stage: prod
  name: kuard
spec:
  replicas: 1
  selector:
    matchLabels:
      run: kuard
  template:
    metadata:
      annotations:
        kubernetes.io/change-cause: "Upgrade to green kuard"
      labels:
        app: cacete-dourado
        run: kuard
    spec:
      containers:
      - name: kuard
        image: "gcr.io/kuar-demo/kuard-amd64:green"
